name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint PHP files
        run: find . -name "*.php" -exec php -l {} \;