name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint PHP files
        run: Get-ChildItem -Path . -Include *.php -Recurse | ForEach-Object { php -l $_ }
        shell: pwsh

      - name: Deploy to server
        if: success()
        run: |
          scp -r * ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.REMOTE_PATH }}/public_html
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd ${{ secrets.REMOTE_PATH }}/public_html && ./deploy.sh'
