name: GitHub Actions Demo
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint PHP files
        run: Get-ChildItem -Path . -Include *.php -Recurse | ForEach-Object { php -l $_ }
        shell: pwsh
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd chibis6b.beget.tech/public_html
            git pull origin master