name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint PHP files
        run: Get-ChildItem -Path . -Include *.php -Recurse | ForEach-Object { php -l $_ }
        shell: pwsh

      - name: Deploy to server
        if: success()
        run: |
          scp -r * chibis6b@chibis6b.beget.tech:/chibis6b.beget.tech/public.html
          ssh chibis6b@chibis6b.beget.tech 'cd /chibis6b.beget.tech/public.html && ./deploy.sh'